name: chrislemmon.ent
favicon: null
layout_spectrum: 0.50016
typography_spectrum: 0.6708910504821688
title: Chris Lemmon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#e4e4e4'
    - '#aeb1ae'
    - '#3d403d'
    - '#6d706d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
